openapi: 3.2.0
info:
  title: Onboarding Salesforce API
  version: 1.0.0
  description: Skedulo Onboarding API
servers:
- url: https://api.skedulo.com/onboarding
- url: https://api.uk.skedulo.com/onboarding
- url: https://api.ca.skedulo.com/onboarding
- url: https://api.au.skedulo.com/onboarding
tags:
- name: Salesforce
paths:
  /salesforce/initialize_tenant:
    post:
      description: Installs package and sets up salesforce connection for a tenant when the user first logs in.
      operationId: initializeTenantSalesforce
      responses:
        '200':
          description: Tenant initialized succesfully.
      tags:
      - Salesforce
      summary: Initialize tenant salesforce
      x-summary-source: derived
components:
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
