overlay: 1.0.0
info:
  title: API Evangelist enhancements for Skedulo Configurations API
  version: 1.0.0
extends: openapi/skedulo-configurations-openapi.yml
actions:
- target: $.info
  update:
    x-apievangelist-provider: skedulo
    x-apievangelist-service: configurations
    x-api-evangelist: https://apis.io/provider/skedulo
